-- This resource was generated by grzyClothTool :)
-- pack made by jim-g
-- https://discord.gg/3a647ze5rn
-- 
-- Disclaimer: I did not make the male judge robe. I can't remember where it's from, but it was a free release. 
-- I just modified the female version a bit in Blender to fit a female body better.
--
fx_version 'cerulean'
game 'gta5'
author 'jim-g'

files {
  'mp_m_freemode_01_judge_robe_fivem_f_and_m_jim_g.meta',
  'mp_f_freemode_01_judge_robe_fivem_f_and_m_jim_g.meta'
}

data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_judge_robe_fivem_f_and_m_jim_g.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_judge_robe_fivem_f_and_m_jim_g.meta'
